Repository RealConrad/42webserv, pull requests merged in 2024-04, with the labels that each got.

#3 added basic html site and styles
  www/index.html
  www/pages/cgi.html
  www/pages/delete.html
  www/pages/get.html
  www/pages/post.html
  www/styles.css
Labels: enhancement

#5 Feat/config manager
  .gitignore
  Makefile
  config/default.config
  config/invalid.config
  includes/ConfigManager.hpp
  includes/Structs.hpp
  includes/Utils.hpp
  src/config-manager/ConfigManager.cpp
  src/main.cpp
  src/utils/utils.cpp
Labels: enhancement

#7 Feat/debug logger
  .gitignore
  Makefile
  includes/Logger.hpp
  src/config-manager/ConfigManager.cpp
  src/logger/Logger.cpp
  src/main.cpp
Labels: enhancement

#9 Improved Logger
  includes/Logger.hpp
  src/config-manager/ConfigManager.cpp
  src/logger/Logger.cpp
  src/main.cpp
Labels: enhancement

#11 Feat/handle client
  Makefile
  config/default.config
  includes/HTTPRequest.hpp
  includes/HTTPResponse.hpp
  includes/SocketManager.hpp
  includes/Structs.hpp
  src/HTTPRequest.cpp
  src/HTTPResponse.cpp
  src/SocketManager.cpp
Labels: enhancement

#23 Http poll wtf
  includes/HTTPRequest.hpp
  includes/SocketManager.hpp
  includes/Utils.hpp
  includes/Utils.tpp
  src/HTTPRequest.cpp
  src/HTTPResponse.cpp
  src/SocketManager.cpp
  src/main.cpp
  src/utils/utils.cpp
  www/favicon.ico
  www/index.html
Labels: bug, enhancement

#40 28 implement delete method
  config/default.config
  config/konrads.config
  includes/HTTPResponse.hpp
  includes/SocketManager.hpp
  includes/Structs.hpp
  src/HTTPResponse.cpp
  src/SocketManager.cpp
  www/index2.html
  www/pages/delete.html
  www/pages/pages.html
  www/pages/post.html
  www/uploads/image2.jpg
  www/uploads/pexels-christian-heitz-842711.jpg
  www/uploads/test
Labels: enhancement

#41 28 implement delete method
  src/HTTPResponse.cpp
  www/pages/delete.html
Labels: enhancement

#42 Http code fix
  .gitignore
  .vscode/settings.json
  config/default.config
  includes/HTTPResponse.hpp
  src/HTTPResponse.cpp
  src/SocketManager.cpp
  www/.hiddenFolder/PedroPedroPedroooo.gif
  www/.hiddenFolder/pedro.html
  www/.hiddenFolder/pedro.mp3
  www/index.html
  www/pages/delete.html
  www/pages/notFound.html
  www/pages/post.html
  www/styles.css
  www/topsecret/short.txt
  www/uploads/image3.jpg
  www/uploads/short.txt
  www/uploads/text.txt
Labels: enhancement

#44 Feat/final cleanup
  Makefile
  config/minimalbad.config
  includes/HTTPRequest.hpp
  includes/HTTPResponse.hpp
  includes/Logger.hpp
  includes/SocketManager.hpp
  includes/Utils.hpp
  src/ConfigManager.cpp
  src/HTTPRequest.cpp
  src/HTTPResponse.cpp
  src/Logger.cpp
  src/SocketManager.cpp
  src/config-manager/ConfigManager.cpp
  src/utils.cpp
  www/better_index.html
  www/cgi/custom_hello.py
  www/index.html
  www/pages/notFound.html
  www/pages/post.html
Labels: documentation, enhancement
